name: Release Branch
on:
  workflow_dispatch:

jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:

      - name: check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.HPCFLOW_ACTIONS_TOKEN || secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Init git config
        run: |
          git config user.name hpcflow-actions
          git config user.email hpcflow-actions@users.noreply.github.com  

      - name: create release branch
        run: git checkout -b release/test-release

      - name: bump version
        run: echo new_version >> version.txt

      - name: update release notes
        run: echo some release notes >> release_notes.txt

      - name: Commit release notes and version files
        id: make-commit
        run: |
          git add versions.txt
          git add release_notes.txt 
          git commit --message "Test commit"

      - name: Push release branch
        run: git push rigin release/test-release

       

